{{ if .Values.nfs.mountOptions -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ template "nfs-client-provisioner.fullname" . }}
  labels: 
    nfs-client-provisioner: {{ template "nfs-client-provisioner.fullname" . }}
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.storageClass.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
  storageClassName: {{ .Values.storageClass.name }}
  {{- if .Values.nfs.mountOptions }}
  mountOptions:
    {{- range .Values.nfs.mountOptions }}
    - {{ . }}
    {{- end }}
  {{- end }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
{{ end -}}
