kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{- include "redis.pvc.fullname" }}
  namespace: {{ .Release.Namespace }}

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{- .Values.pvc.resources.requests.storage }}
  storageClassName: {{- .Values.pvc.storageClassName }}