apiVersion: v1
appVersion: 1.1.0
description: Helm chart for sidecar injector webhook deployment
icon: https://istio.io/favicons/android-192x192.png
keywords:
- istio
- sidecarInjectorWebhook
name: sidecarInjectorWebhook
sources:
- http://github.com/istio/istio
version: 1.1.0
