apiVersion: v1
appVersion: 1.1.0
description: Helm chart for deploying Istio gateways
icon: https://istio.io/favicons/android-192x192.png
keywords:
- istio
- ingressgateway
- egressgateway
- gateways
name: gateways
sources:
- http://github.com/istio/istio
version: 1.1.0
