apiVersion: v1
appVersion: 1.1.0
description: Helm chart for all istio components
icon: https://istio.io/favicons/android-192x192.png
keywords:
- istio
- security
- sidecarInjectorWebhook
- mixer
- pilot
- galley
name: istio
sources:
- http://github.com/istio/istio
version: 1.1.0
