apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "centrifugo.config.fullname" . }}
  labels:
    app: {{ template "centrifugo.config.fullname" . }}
    chart: {{ template "centrifugo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |
    {
      "v3_use_offset": true,
      "token_hmac_secret_key": "my_secret",
      "api_key": "my_api_key",
      "admin_password": "password",
      "admin_secret": "secret",
      "admin": true
    }
