apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.config.fullname" . }}
  labels:
    app: {{ template "wordpress.config.fullname" . }}
    chart: {{ template "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  uploads.ini: |
    file_uploads = On
    memory_limit = 64M
    upload_max_filesize = 64M
    post_max_size = 64M
    max_execution_time = 600
